---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cilium
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: kube-system
  path: "./kubernetes/apps/kube-system/cilium/app"
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cilium-config
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cilium
  targetNamespace: kube-system
  path: "./kubernetes/apps/kube-system/cilium/config"
  dependsOn:
    - name: cilium
      namespace: kube-system
