---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name kgateway-crds
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/kgateway/crds"
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name kgateway
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/kgateway/app"
  wait: true
  dependsOn:
    - name: kgateway-crds
      namespace: networking-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name kgateway-config
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kgateway
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/kgateway/config"
  wait: true
  dependsOn:
    - name: kgateway
      namespace: networking-system
    - name: cert-manager
      namespace: security-system
    - name: onepassword-connect
      namespace: security-system
