---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name dify-proxy
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/dify/proxy"
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name dify-database
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/dify/database"
  wait: true
  dependsOn:
    - name: dify-proxy
      namespace: selfhosted-apps
    - name: cnpg-cluster
      namespace: database-system
    - name: dragonfly-operator
      namespace: database-system
  components:
    - ../../../../components/cnpg
    - ../../../../components/dragonfly
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name dify-sandbox
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/dify/sandbox"
  dependsOn:
    - name: dify-database
      namespace: selfhosted-apps
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name dify-app
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/dify/app"
  dependsOn:
    - name: dify-database
      namespace: selfhosted-apps
    - name: cnpg-cluster
      namespace: database-system
  components:
    - ../../../../components/cnpg
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: ceph-filesystem-snapshot
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name dify-web
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/dify/web"
  dependsOn:
    - name: dify-app
      namespace: selfhosted-apps
