---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name externaldns-cloudflare
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/externaldns-cloudflare/app"
  dependsOn:
    - name: onepassword-connect
      namespace: security-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: externaldns-cloudflare
      namespace: networking-system
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: cloudflare
      namespace: networking-system
