---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name netbox
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/netbox/app"
  dependsOn:
    - name: cnpg-cluster
      namespace: database-system
    - name: dragonfly-operator
      namespace: database-system
  components:
    - ../../../../components/cnpg
    - ../../../../components/dragonfly
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: ceph-filesystem-snapshot
