---
services:
  dockge:
    image: "louislam/dockge:1.5.0"
    container_name: "dockge"
    restart: "unless-stopped"
    ports:
      - "5002:5001/tcp"
    environment:
      - "TZ=Asia/Shanghai"
      - "HOST_HOSTNAME=dockge"
      - "HOST_CONTAINERNAME=dockge"
      - "DOCKGE_STACKS_DIR=/opt/stacks"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DOCKER_ROOT}/dockge/data:/app/data"
      - "${DOCKER_ROOT}/dockge/stacks:/opt/stacks"
