---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name audiomuse
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: media-apps
  path: "./kubernetes/apps/media-apps/audiomuse/app"
  dependsOn:
    - name: cnpg-cluster
      namespace: database-system
    - name: dragonfly-operator
      namespace: database-system
    - name: nfs-shared
      namespace: media-apps
    - name: ollama
      namespace: selfhosted-apps
  components:
    - ../../../../components/cnpg
    - ../../../../components/dragonfly
  postBuild:
    substitute:
      APP: *name
