---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name grafana-operator
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: monitoring-system
  path: "./kubernetes/apps/monitoring-system/grafana/app"
  wait: true
  dependsOn:
    - name: onepassword-connect
      namespace: security-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name grafana-cluster
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: monitoring-system
  path: "./kubernetes/apps/monitoring-system/grafana/cluster"
  dependsOn:
    - name: grafana-operator
      namespace: monitoring-system
    - name: cnpg-cluster
      namespace: database-system
  components:
    - ../../../../components/cnpg
  postBuild:
    substitute:
      APP: grafana
