---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cnpg-operator
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: database-system
  path: ./kubernetes/apps/database-system/cnpg-operator/app
  wait: true
  dependsOn:
    - name: onepassword-connect
      namespace: security-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cnpg-barman
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: database-system
  path: ./kubernetes/apps/database-system/cnpg-operator/barman
  wait: true
  dependsOn:
    - name: cnpg-operator
      namespace: database-system
    - name: cert-manager
      namespace: security-system
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name cnpg-cluster
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: database-system
  path: ./kubernetes/apps/database-system/cnpg-operator/cluster
  wait: true
  dependsOn:
    - name: cnpg-barman
      namespace: database-system
    - name: rook-ceph-cluster
      namespace: storage-system
