---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name mosquitto
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: database-system
  path: ./kubernetes/apps/database-system/mosquitto/app
  wait: true
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
