---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name stirling-pdf
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/stirling-pdf/app"
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
