---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name flux-instance
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: gitops-system
  path: ./kubernetes/apps/gitops-system/flux-instance/app
  prune: false # Never delete this
  wait: true
  dependsOn:
    - name: flux-operator
      namespace: gitops-system
