---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name falco
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: security-system
  path: "./kubernetes/apps/security-system/falco/app"
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name falcosidekick
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: security-system
  path: "./kubernetes/apps/security-system/falco/sidekick"
  wait: true
  dependsOn:
    - name: falco
      namespace: security-system
    - name: dragonfly-operator
      namespace: database-system
  components:
    - ../../../../components/dragonfly
  postBuild:
    substitute:
      APP: *name
